config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get "/jogos", to: 'jogos#index'
  get "/aposta/new", to: 'bet#new'
  get "/aposta/index", to: 'bet#index'
  get "/ranking", to: "ranking#index"
  post '/aposta/create', to: 'bet#create'
  root to: 'home#index' 
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :user
  belongs_to :jogo
  attr_accessor :resultado_time1
  attr_accessor :resultado_time2
  
  validates :valor, numericality: { :greater_than_or_equal_to => 200 }
  
  def self.verificar_vencedores
    
    @jogos = Jogo.where(status: true).last(4)
    
    @jogos.each do |jogo|
      
      apostas_vencedoras = 0
      vencedores = Array.new
      perdedores = 0
      coin_apostado = 0
      coin_final = 0
      porcentagem = 0
      vencedores_total_coin = 0

      @apostas = Bet.where(jogo_id: jogo.id)
      
      @apostas.each do |aposta|
        
        if aposta.resultado == jogo.resultado
          vencedores << aposta.user_id
          apostas_vencedoras << aposta.id
          vencedores_total_coin = vencedores_total_coin + aposta.valor
        else
          perdedores = perdedores + aposta.valor
        end
        
      end
      
        puts "vencedores " + vencedores.length.to_s
        puts "perdedores " + perdedores.to_s
        puts "vencedores_total_coin " + vencedores_total_coin.to_s
        
        vencedores.each do |vencedor|
          coin_atual = User.find(vencedor).coin
          coin_apostado = Bet.where(user_id: vencedor, jogo_id: jogo.id).take
          porcentagem = coin_apostado.valor.to_f / vencedores_total_coin
          puts "porcentagem " + porcentagem.to_s
          puts "coin_atual " + coin_atual.to_s
          coin_final = coin_atual + coin_apostado.valor + ( perdedores * porcentagem )
          puts "coin final: " + coin_final.to_s
          User.update(vencedor, :coin => coin_final)
          aposta_vencedora = Bet.where(jogo_id: jogo.id, user_id: vencedor).take
          Bet.update(aposta_vencedora.id, :ganhou_qnt =>  coin_apostado.valor + ( perdedores * porcentagem ) )
        end
    
    end
  
  end
end

app/controllers/bet_controller.rb
class BetController < ApplicationController
  before_action :apostas_duplicadas, only: [:new]
  
  def new
    @bet = Bet.new
    @jogo = Jogo.find(params[:id])
  end
  
  def create
    if params[:bet][:valor].to_i > current_user.coin.to_i || params[:bet][:valor] == ''
      erro = true
      flash[:danger] = 'Você não tem coins suficiente!'
      redirect_to "/aposta/new?id=#{params[:bet][:jogo_id]}"
    else

      case params[:bet][:resultado_time1]
        when 'vitoria'
          @jogo = Jogo.find(params[:bet][:jogo_id])
          total = @jogo.contagem_vit1 + params[:bet][:valor].to_i
          Jogo.update(params[:bet][:jogo_id], :contagem_vit1 => total)
          resultado = -1
        when 'empate'
          @jogo = Jogo.find(params[:bet][:jogo_id])
          total = @jogo.contagem_empate + params[:bet][:valor].to_i
          Jogo.update(params[:bet][:jogo_id], :contagem_empate => total)          
          resultado = 0
        when 'derrota'
          @jogo = Jogo.find(params[:bet][:jogo_id])
          total = @jogo.contagem_vit2 + params[:bet][:valor].to_i
          Jogo.update(params[:bet][:jogo_id], :contagem_vit2 => total)          
          resultado = 1
        when 'null'
          erro = true
          flash[:danger] = 'Selecione um resultado!'
          redirect_to "/aposta/new?id=#{params[:bet][:jogo_id]}"
        else
          erro = true
          flash[:danger] = 'Erro'
          redirect_to "/aposta/new?id=#{params[:bet][:jogo_id]}"
      end
    
      if !erro 
        @bet = Bet.new(params.require(:bet).permit(:user_id, :jogo_id, :valor))
        @bet.resultado = resultado
    
        if @bet.save
          @user = User.find(current_user.id)
          new_coin = @user.coin - params[:bet][:valor].to_i
          User.update(current_user.id, :coin => new_coin)

          
          flash[:success] = 'Aposta feita com sucesso'
          redirect_to '/jogos'
        end
      end
      
    end  
  end

  def index
    @bet = Bet.where(user_id: current_user.id).order(id: :desc)
  end 
  
  def apostas_duplicadas
    @duplicada = Bet.where(jogo_id: params[:id], user_id: current_user.id).take
    if !@duplicada.nil?
      redirect_to '/jogos'
    end
  end
  
end

  

app/helpers/bet_helper.rb
module BetHelper
  def get_jogo(id)
    Jogo.find(id)
  end
end

app/views/bet/index.html.erb
<div class="container">
  <% @bet.each do |bet| %>
    <h4> Semana <%= get_jogo(bet.jogo_id).semana %></h4>
    <div class="minhas_apostas">
      <div id="time1_minhas">
        <p> <%= get_jogo(bet.jogo_id).time1 %> </p>
        <%= image_tag(get_jogo(bet.jogo_id).time1[0..2].downcase, height: '100', width: '100') %>
      </div>
      
      <div id="middle_minhas">
        <% if bet.resultado == -1 %>
          2 x 0
        <% elsif bet.resultado == 0 %>
          1 x 1
        <% else %>
          0 x 2
        <% end %>
      </div>
      
      <div id="time2_minhas">
        <p> <%= get_jogo(bet.jogo_id).time2 %> </p>
        <%= image_tag(get_jogo(bet.jogo_id).time2[0..2].downcase, height: '100', width: '100' ) %>
      </div>
  
      <div id="coin_minhas">
        <p> <%= get_jogo(bet.jogo_id).data %> </p>
        <br>
        <p> <%= bet.valor%> <%= image_tag("coin.png", height: '25', width: '25')%> </p>
        <br>
        <% if get_jogo(bet.jogo_id).status == false || get_jogo(bet.jogo_id).resultado == nil%>
          <span class="label label-default">Jogo nao terminou</span>
        <% else %>
          <% if get_jogo(bet.jogo_id).resultado == bet.resultado %>
            <span class="label label-success">Voce ganhou <%= bet.ganhou_qnt %> </span>
          <% else %>
            <span class="label label-danger"> Voce perdeu </span>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/bet/new.html.erb
  <div class="container">
    <div class="aposta">
      <%= form_for(@bet, url: aposta_create_path) do |f| %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :jogo_id, :value => params[:id] %>
        
        <div id="time1_aposta">
          <p> <%= @jogo.time1 %> </p>
          <%= image_tag(@jogo.time1[0..2].downcase, height: '300', width: '300') %>
          <%= f.select(:resultado_time1, [['Resultado','null'], ['Vitória','vitoria'], ['Empate','empate'], ['Derrota','derrota']], {}, { class: 'form-control aposta-select'})%>  
          
        </div>
        
        <div id="middle_aposta">
          <%= f.label :valor %> <span id="min">minimo: 200</span>
          <%= f.number_field :valor, :value => 200, min: 200, class:'form-control' %>
        </div>
        
        <div id="time2_aposta">
          <p> <%= @jogo.time2 %> </p>
          <%= image_tag(@jogo.time2[0..2].downcase, height: '300', width: '300' ) %>
          <%= f.select(:resultado_time2, [['Resultado','null'], ['Vitória','vitoria'], ['Empate','empate'], ['Derrota','derrota']], {}, { class: 'form-control aposta-select'})%>  
        </div>
  </div>
    <%= f.submit "Enviar", class: "btn btn-success aposta-button" %>
    <% end %>
</div>