config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get "/jogos", to: 'jogos#index'
  get "/aposta/new", to: 'bet#new'
  get "/aposta/index", to: 'bet#index'
  get "/ranking", to: "ranking#index"
  post '/aposta/create', to: 'bet#create'
  root to: 'home#index' 
end

app/models/jogo.rb
class Jogo < ApplicationRecord
    has_many :bets
end

app/controllers/jogos_controller.rb
class JogosController < ApplicationController
  def index
    @jogo = Jogo.where(status: false).first(4)
  end  
end

app/helpers/jogos_helper.rb
module JogosHelper
  def get_bets(user_id, jogo_id)
    Bet.where(user_id: user_id, jogo_id: jogo_id).take
  end
end

app/views/jogos/index.html.erb
<div class="container">
  <div id="header-jogos">
    <h1>Semana <%= @jogo[0].semana %> </h1>
    <p id="fim-aposta"> As apostas dessa semana serao encerradas no dia: <%= @jogo[0].data - 1 %></p>
  </div>
  
  <% @jogo.each do |jogo| %>
    
    <div class="card">
      <div id="time1">
        <p> <%= jogo.time1 %> </p>
        <%= image_tag(jogo.time1[0..2].downcase, height: '150', width: '150px') %>
      </div>
      
      <div id="middle">
        <% if user_signed_in? %>
          <% if get_bets(current_user.id, jogo.id) %>
            <button class="btn btn-warning" disabled> Aposte </button>
          <% else %>
            <%= link_to 'Aposte', aposta_new_path(:id => jogo.id), :class => "btn btn-success" %>
          <% end %>
        <% else %>
          <%= link_to 'Aposte', new_user_session_path, :class => "btn btn-success" %>
        <% end %>
      </div>
      
      <div id="time2">
        <p> <%= jogo.time2 %> </p>
        <%= image_tag(jogo.time2[0..2].downcase, height: '150', width: '150px' ) %>
      </div>
    </div>
    
  <% end %>

</div>